### ISSUE TITLE
Cache output

### ISSUE THREAD

**Issue by chpio** [jussi-kalliokoski/gulp-spa#8]
Hi,

is there a possibility for caching the handled files when you run spa over more than one html file?

**Comment by jussi-kalliokoski** [comment]
Hi! There is no built-in way of doing this at the moment; maybe it would be worth adding, but it can already be done in user code by creating a caching collector stream. However, that's quite tedious to get right and also doesn't prevent gulp-spa from reading the source files multiple times.

I'll take a shot at implementing this later this week. Thanks for the suggestion!

**Comment by chpio** [comment]
Thank you for your response.

**Comment by jussi-kalliokoski** [comment]
The first step would probably be putting a no-op stream in between what gets passed to the method specified in the pipelines option. Then, we can pipe to that no-op stream only if a certain condition is met.

Then, perhaps add a second argument to the pipeline methods that contains the context of the operation, where you can say for example `context.readSources = false` which would prevent the files from being read. This would better allow the user side caching and a lower level of control for the user in general.

Then, we could also introduce `context.cache()` which would make sure that the result of the pipeline method is cached instead of creating a new one for each file.

**Comment by chpio** [comment]
Also there should be a flag for not caching data between gulp runs (eg in watch), but only inside a run (between multiple html files)
